/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_callback_DataProvider2 */

#ifndef _Included_com_kenny_callback_DataProvider2
#define _Included_com_kenny_callback_DataProvider2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_callback_DataProvider2
 * Method:    call_dataprovider_method
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kenny_callback_DataProvider2_call_1dataprovider_1method
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
