/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_HelloWorld */

#ifndef _Included_com_demo_HelloWorld
#define _Included_com_demo_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_HelloWorld
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_HelloWorld_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_demo_HelloWorld
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_HelloWorld_hello_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
