/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_MainActivity */

#ifndef _Included_com_demo_MainActivity
#define _Included_com_demo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_MainActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_MainActivity_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_demo_MainActivity
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_MainActivity_hello_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
