/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_monitor_MainActivity */

#ifndef _Included_com_kenny_monitor_MainActivity
#define _Included_com_kenny_monitor_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_monitor_MainActivity
 * Method:    getPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kenny_monitor_MainActivity_getPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
