/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_jni_c_c_MainActivity */

#ifndef _Included_com_kenny_jni_c_c_MainActivity
#define _Included_com_kenny_jni_c_c_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_jni_c_c_MainActivity
 * Method:    helloInC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kenny_jni_1c_1c_MainActivity_helloInC__
  (JNIEnv *, jobject);

/*
 * Class:     com_kenny_jni_c_c_MainActivity
 * Method:    helloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kenny_jni_1c_1c_MainActivity_helloInC__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
