/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_ndk_DataProvider */

#ifndef _Included_com_kenny_ndk_DataProvider
#define _Included_com_kenny_ndk_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_ndk_DataProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kenny_ndk_DataProvider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kenny_ndk_DataProvider
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kenny_ndk_DataProvider_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kenny_ndk_DataProvider
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kenny_ndk_DataProvider_intMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_kenny_ndk_DataProvider
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kenny_ndk_DataProvider_sub
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
