/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_jnilogin_MainActivity */

#ifndef _Included_com_kenny_jnilogin_MainActivity
#define _Included_com_kenny_jnilogin_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_jnilogin_MainActivity
 * Method:    call_login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kenny_jnilogin_MainActivity_call_1login
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
