/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenny_callback_DataProvider */

#ifndef _Included_com_kenny_callback_DataProvider
#define _Included_com_kenny_callback_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenny_callback_DataProvider
 * Method:    callmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kenny_callback_DataProvider_callmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_kenny_callback_DataProvider
 * Method:    callmethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kenny_callback_DataProvider_callmethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_kenny_callback_DataProvider
 * Method:    callmethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kenny_callback_DataProvider_callmethod3
  (JNIEnv *, jobject);

/*
 * Class:     com_kenny_callback_DataProvider
 * Method:    callmethod4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kenny_callback_DataProvider_callmethod4
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
